version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: "test"
    working_directory: ~/avrokado
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
