version: 2
jobs:
  build:
    working_directory: ~/avrokado
    machine:
        enabled: true
        docker_layer_caching: true
    steps:
      - checkout
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          nvm install v10
          nvm alias default v10
      - run: |
          if [[ ! -d "$HOME/.yarn" ]]; then
            curl -o- -L https://yarnpkg.com/install.sh | bash;
          fi
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run: pip install docker-compose~=1.23.0
      - run: sudo apt-get update && sudo apt-get -y install libsasl2-dev libssl-dev
      - run: echo 127.0.0.1 kafka | sudo tee -a /etc/hosts
      - run: docker-compose up -d
      - run: yarn install
      - run: yarn lint
      - run: yarn test && yarn codecov
  publish:
    working_directory: ~/avrokado
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/avrokado/.npmrc
      - run: yarn publish
workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
            branches:
              ignore: /.*/
